In [1]:
import random
import numpy as np
from read_imageset import read_imageset_arrays
from build_autoencoder import build_autoencoder
from show_original_decoded import show_original_decoded

Using TensorFlow backend.


In [2]:
sz = 128
dataset_name = 'LIDC-IDRI'
x_train = read_imageset_arrays(dataset_name, sz, 0.95)
np.random.shuffle(x_train)

loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0001_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0002_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0003_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0004_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0005_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0006_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0007_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0008_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0009_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0010_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0011_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0012_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0013_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0014_20000101.npy
loadin

loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0122_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0123_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0124_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0125_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0126_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0127_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0128_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0129_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0130_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0131_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0132_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0133_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0134_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0135_20000101.npy
loadin

loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0250_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0252_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0253_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0254_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0255_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0256_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0257_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0258_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0259_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0260_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0261_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0262_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0263_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0264_20000101.npy
loadin

loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0371_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0372_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0373_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0374_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0375_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0376_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0377_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0379_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0380_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0381_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0382_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0383_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0384_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0385_20000101.npy
loadin

loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0496_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0497_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0498_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0499_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0500_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0501_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0502_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0503_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0504_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0505_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0506_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0507_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0508_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0509_20000101.npy
loadin

loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0616_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0618_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0619_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0620_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0621_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0622_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0623_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0624_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0625_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0626_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0627_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0628_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0629_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0631_20000101.npy
loadin

loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0743_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0744_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0745_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0746_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0747_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0748_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0750_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0751_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0752_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0753_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0754_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0755_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0756_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0757_20000101.npy
loadin

loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0866_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0867_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0868_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0869_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0870_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0872_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0873_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0874_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0875_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0876_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0877_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0878_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0879_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0880_20000101.npy
loadin

loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0990_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0991_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0992_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0994_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0995_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0996_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0997_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0998_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-0999_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-1000_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-1001_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-1002_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-1003_20000101.npy
loading dataset:  .\data\LIDC-IDRI\128x128\LIDC-IDRI-1004_20000101.npy
loadin

In [3]:
test_count = int(len(x_train)/10)
x_test = x_train[:test_count]
x_train = x_train[test_count:]
x_train, x_test = np.array(x_train), np.array(x_test)

In [4]:
x_train.shape, x_test.shape

((861, 128, 128, 1), (95, 128, 128, 1))

In [5]:
autoencoder, encode_only, decode_only = build_autoencoder(sz, 'adadelta', 'binary_crossentropy')

Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 128, 128, 1)  0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 128, 128, 32) 320         input_1[0][0]                    
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 64, 64, 32)   0           conv2d_1[0][0]                   
__________________________________________________________________________________________________
spatial_dropout2d_1 (SpatialDro (None, 64, 64, 32)   0           max_pooling2d_1[0][0]            
____________________________________________________________________________________________

In [23]:
autoencoder.fit(x_train, x_train, 
                epochs=125, batch_size=256, 
                shuffle=True, validation_data=(x_test,x_test))

Train on 861 samples, validate on 95 samples
Epoch 1/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2832 - val_loss: 0.3032
Epoch 2/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2871 - val_loss: 0.3041
Epoch 3/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2886 - val_loss: 0.3025
Epoch 4/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2847 - val_loss: 0.3010
Epoch 5/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2848 - val_loss: 0.3000
Epoch 6/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2850 - val_loss: 0.2990
Epoch 7/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2835 - val_loss: 0.3005
Epoch 8/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2844 - val_loss: 0.2986
Epoch 9/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2841 - val_loss: 0.2997
Epoch 10/125
861/861 [========================

Epoch 81/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2804 - val_loss: 0.2955
Epoch 82/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2797 - val_loss: 0.2979
Epoch 83/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2805 - val_loss: 0.2971
Epoch 84/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2804 - val_loss: 0.3014
Epoch 85/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2827 - val_loss: 0.2970
Epoch 86/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2803 - val_loss: 0.2968
Epoch 87/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2800 - val_loss: 0.2975
Epoch 88/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2796 - val_loss: 0.2965
Epoch 89/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2798 - val_loss: 0.2967
Epoch 90/125
861/861 [==============================] - 1s 1ms/step - loss: 0.2791

In [7]:
# save the model(s)
autoencoder.save('models/autoencoder.h5')
encode_only.save('models/encode_only.h5')
decode_only.save('models/decode_only.h5')

In [24]:
encode_only_imgs = encode_only.predict(x_test)
for n in range(10):
    print("shape of encoded = ", encode_only_imgs[2].shape)
    hist, bins = np.histogram(encode_only_imgs[2])
    print(hist)
    print(bins)

shape of encoded =  (95, 8)
[  6  25  36  94 149 204 132  82  25   7]
[-45.56327   -37.317345  -29.071419  -20.825493  -12.579567   -4.333641
   3.9122849  12.158211   20.404137   28.650063   36.89599  ]
shape of encoded =  (95, 8)
[  6  25  36  94 149 204 132  82  25   7]
[-45.56327   -37.317345  -29.071419  -20.825493  -12.579567   -4.333641
   3.9122849  12.158211   20.404137   28.650063   36.89599  ]
shape of encoded =  (95, 8)
[  6  25  36  94 149 204 132  82  25   7]
[-45.56327   -37.317345  -29.071419  -20.825493  -12.579567   -4.333641
   3.9122849  12.158211   20.404137   28.650063   36.89599  ]
shape of encoded =  (95, 8)
[  6  25  36  94 149 204 132  82  25   7]
[-45.56327   -37.317345  -29.071419  -20.825493  -12.579567   -4.333641
   3.9122849  12.158211   20.404137   28.650063   36.89599  ]
shape of encoded =  (95, 8)
[  6  25  36  94 149 204 132  82  25   7]
[-45.56327   -37.317345  -29.071419  -20.825493  -12.579567   -4.333641
   3.9122849  12.158211   20.404137   28.6

In [25]:
decoded_imgs = decode_only.predict(encode_only_imgs[2])
show_original_decoded(x_test, decoded_imgs, sz)

In [ ]:
import scipy.ndimage
zoom = scipy.ndimage.zoom(x_test[0].reshape(128,128), 2.0, order=5)
zoom.shape

In [ ]:
# add random values to decoded
for n in range(8):
    perturb_vectors = np.zeros(encode_only_imgs[2].shape)
    perturb_element = -120.0 # * np.random.standard_normal()
    perturb_vectors[:,n] = perturb_element
    encode_only_imgs_z = np.add(encode_only_imgs[2], perturb_vectors)

    decoded_imgs = decode_only.predict(encode_only_imgs_z)
    show_original_decoded(x_test, decoded_imgs, sz)

In [ ]:
# add random values to decoded
perturb_vectors = np.random.standard_normal(size=encode_only_imgs[2].shape)
perturb_vectors = np.multiply(perturb_vectors, 15.8)
encode_only_imgs_z = np.add(encode_only_imgs[2], perturb_vectors)

decoded_imgs = decode_only.predict(encode_only_imgs_z)
show_original_decoded(x_test, decoded_imgs, sz)

In [ ]:
random_encoded = 0.0 * np.random.standard_normal(size=encode_only_imgs[2].shape)
print(random_encoded.shape)
print(type(random_encoded))
decoded_imgs_original = decode_only.predict(random_encoded)

perturb_vectors = np.random.standard_normal(size=encode_only_imgs[2].shape)
perturb_vectors = np.multiply(perturb_vectors, 5.0)
decoded_imgs_perturbed = decode_only.predict(np.add(random_encoded, perturb_vectors))

show_original_decoded(decoded_imgs_original, decoded_imgs_perturbed, sz)

In [19]:
import matplotlib.pyplot as plt
def g(**kwargs):
    plt.figure(2)
    # x = np.linspace(-10,10,num=1000)
    # plt.plot(x,kwargs['1']/100*x + kwargs['2'])
    # plt.ylim(-5,5)
    # plt.show()
    latent = np.array([list(kwargs.values())])
    # print(type(latent))
    # print(latent.shape)
    # latent.reshape(1,)
    # print(latent)
    decoded = decode_only.predict(latent)
    plt.imshow(decoded.reshape(sz,sz))
    plt.gray()
    return kwargs['1']

In [20]:
from ipywidgets import interactive_output,Layout
import ipywidgets as widgets

In [21]:
%matplotlib inline
latent_dim = encode_only_imgs[2].shape[-1]
kwargs = {str(k):widgets.IntSlider(value=0,min=-20,max=20,orientation='vertical',layout=Layout(padding='0%')) for k in range(latent_dim)}
w = interactive_output(g,kwargs)
display(widgets.HBox(list(kwargs.values()),layout=Layout(padding='0%')),w)

Output()

In [ ]:
encode_only_imgs[2].shape